CREATE TABLE STATUS (
    ID NUMBER (2) NOT NULL ,
    NAME VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
  ) ;
ALTER TABLE STATUS ADD CONSTRAINT STATUS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE EDUCATIONAL_INSTITUTION (
    ID NUMBER (10) NOT NULL ,
    NAME VARCHAR2(1000) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    REMOVED_AT TIMESTAMP NULL
  ) ;
ALTER TABLE EDUCATIONAL_INSTITUTION ADD CONSTRAINT EDUCATIONAL_INSTITUTION_PK PRIMARY KEY ( ID ) ;

CREATE TABLE ACCOUNT (
    ID NUMBER (6) NOT NULL ,
    NAME VARCHAR2(200) NOT NULL,    
    UERNAME VARCHAR2(200) NOT NULL,
    PASSWORD VARCHAR2(200) NOT NULL,
    PHOTO BLOB NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    REMOVED_AT TIMESTAMP NULL
  ) ;
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY ( ID ) ;

CREATE TABLE COURSE (
    ID NUMBER (6) NOT NULL ,
    NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(4000) NOT NULL,
    EDUCATIONAL_INSTITUTION_ID NUMBER (10) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    REMOVED_AT TIMESTAMP NULL
  ) ;
ALTER TABLE COURSE ADD CONSTRAINT COURSE_PK PRIMARY KEY ( ID ) ;

CREATE TABLE LESSON (
    ID NUMBER (6) NOT NULL ,
    NAME VARCHAR2(200) NOT NULL,
    COURSE_ID NUMBER (10) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    REMOVED_AT TIMESTAMP NULL
  ) ;
ALTER TABLE LESSON ADD CONSTRAINT LESSON_PK PRIMARY KEY ( ID ) ;

CREATE TABLE MY_COURSE (
    ID NUMBER (6) NOT NULL ,
    NAME VARCHAR2(200) NOT NULL,
    ACCOUNT_ID NUMBER (6) NOT NULL,
    COURSE_ID NUMBER (6) NOT NULL,
    STATUS_ID NUMBER (6) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    REMOVED_AT TIMESTAMP NULL
  ) ;
ALTER TABLE MY_COURSE ADD CONSTRAINT MY_COURSE_PK PRIMARY KEY ( ID ) ;

CREATE TABLE MY_LESSON (
    ID NUMBER (6) NOT NULL ,
    NAME VARCHAR2(200) NOT NULL,
    MY_COURSE_ID NUMBER (6) NOT NULL,
    STATUS_ID NUMBER (6) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    REMOVED_AT TIMESTAMP NULL
  ) ;
ALTER TABLE MY_LESSON ADD CONSTRAINT MY_LESSON_PK PRIMARY KEY ( ID ) ;

ALTER TABLE COURSE ADD CONSTRAINT COURSE_EDUCATIONAL_INSTITUT_FK FOREIGN KEY ( EDUCATIONAL_INSTITUTION_ID ) REFERENCES EDUCATIONAL_INSTITUTION ( ID ) ;

ALTER TABLE LESSON ADD CONSTRAINT LESSON_COURSE_FK FOREIGN KEY ( COURSE_ID ) REFERENCES COURSE ( ID ) ;

ALTER TABLE MY_COURSE ADD CONSTRAINT MY_COURSE_ACCOUNT_FK FOREIGN KEY ( ACCOUNT_ID ) REFERENCES ACCOUNT ( ID ) ;
ALTER TABLE MY_COURSE ADD CONSTRAINT MY_COURSE_COURSE_FK FOREIGN KEY ( COURSE_ID ) REFERENCES COURSE ( ID ) ;
ALTER TABLE MY_COURSE ADD CONSTRAINT MY_COURSE_STATUS_FK FOREIGN KEY ( STATUS_ID ) REFERENCES STATUS ( ID ) ;

ALTER TABLE MY_LESSON ADD CONSTRAINT MY_LESSON_MY_COURSE_FK FOREIGN KEY ( MY_COURSE_ID ) REFERENCES ACCOUNT ( ID ) ;
ALTER TABLE MY_LESSON ADD CONSTRAINT MY_LESSON_STATUS_FK FOREIGN KEY ( STATUS_ID ) REFERENCES STATUS ( ID ) ;