CREATE TABLE STATUS (
    ID NUMBER (2) NOT NULL ,
    NAME VARCHAR2(100) NOT NULL
  ) ;
ALTER TABLE STATUS ADD CONSTRAINT STATUS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE EDUCATIONAL_INSTITUTION (
    ID NUMBER (10) NOT NULL ,
    NAME VARCHAR2(1000) NOT NULL
  ) ;
ALTER TABLE EDUCATIONAL_INSTITUTION ADD CONSTRAINT EDUCATIONAL_INSTITUTION_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PROFILE (
    ID NUMBER (6) NOT NULL ,
    NAME VARCHAR2(200) NOT NULL,    
    USERNAME VARCHAR2(200) NOT NULL,
    PASSWORD VARCHAR2(200) NOT NULL,
    PHOTO BLOB NOT NULL
  ) ;
ALTER TABLE PROFILE ADD CONSTRAINT PROFILE_PK PRIMARY KEY ( ID ) ;

CREATE TABLE COURSE (
    ID NUMBER (6) NOT NULL ,
    NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(4000) NOT NULL,
    EDUCATIONAL_INSTITUTION_ID NUMBER (10) NOT NULL,
    STATUS_ID NUMBER (2) NOT NULL,
    PROFILE_ID NUMBER (6) NOT NULL
  ) ;
ALTER TABLE COURSE ADD CONSTRAINT COURSE_PK PRIMARY KEY ( ID ) ;

CREATE TABLE LESSON (
    ID NUMBER (6) NOT NULL ,
    NAME VARCHAR2(200) NOT NULL,
    AT_UPDATE TIMESTAMP NOT NULL,
    COURSE_ID NUMBER (10) NOT NULL,
    STATUS_ID NUMBER (2) NOT NULL
  ) ;
ALTER TABLE LESSON ADD CONSTRAINT LESSON_PK PRIMARY KEY ( ID ) ;

ALTER TABLE COURSE ADD CONSTRAINT COURSE_EDUCATIONAL_INSTITUT_FK FOREIGN KEY ( EDUCATIONAL_INSTITUTION_ID ) REFERENCES EDUCATIONAL_INSTITUTION ( ID ) ;
ALTER TABLE COURSE ADD CONSTRAINT COURSE_STATUS_FK FOREIGN KEY ( STATUS_ID ) REFERENCES STATUS ( ID ) ;
ALTER TABLE COURSE ADD CONSTRAINT COURSE_PROFILE_FK FOREIGN KEY ( PROFILE_ID ) REFERENCES PROFILE ( ID ) ;

ALTER TABLE LESSON ADD CONSTRAINT LESSON_COURSE_FK FOREIGN KEY ( COURSE_ID ) REFERENCES COURSE ( ID ) ;
ALTER TABLE LESSON ADD CONSTRAINT LESSON_STATUS_FK FOREIGN KEY ( STATUS_ID ) REFERENCES STATUS ( ID ) ;